# Generated by Django 5.0.2 on 2024-08-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_transcription"),
    ]

    operations = [
        migrations.AddField(
            model_name="transcription",
            name="original_audio_filename",
            field=models.CharField(default="One", max_length=255),
            preserve_default=False,
        ),
    ]
