# Generated by Django 5.0.2 on 2024-09-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_audiofile_original_filename"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transcription",
            name="audio_file",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="transcription",
            name="original_audio_filename",
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
